### PR TITLE
Emacs article.

### PR DESCRIPTION
**Pull request by proofit404**
Hello. I need to say that my English is really poor. Take extra attintion to your review.

Thanks.

### CODE REVIEW

**Comment by makaimc** [comment]
Thank you @proofit404! I'm on vacation at the moment but as soon as I get a chance I'll merge, clean up the English and get it live.

**Comment by proofit404** [comment]
Thanks a lot!

**Comment by makaimc** [comment]
Thanks again @proofit404. I'm going to merge this and I'll edit the English for clarity. Should be up on the site later today.

**Comment by makaimc** [comment]
The [Emacs page](http://www.fullstackpython.com/emacs.html) is live! I'll add more resources to it when I do further research on editing Python code with Emacs. Thanks again!

**Comment by proofit404** [comment]
Thanks for correction!

**Pull request merged**
